"""GitHub Actions integration for Greybeard.

This module provides utilities for running Greybeard reviews in GitHub Actions,
including:
- Risk detection and PR blocking logic
- PR comment formatting and posting
- GitHub Check status creation
- Multi-pack review handling
- Environment variable configuration
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .analyzer import run_review
from .config import GreybeardConfig
from .models import ReviewRequest
from .packs import load_pack

# Risk threshold patterns for PR blocking
RISK_PATTERNS = {
    "high": (r"production incident|data loss|security vulnerability|" r"cascading failure"),
    "medium": (
        r"production incident|data loss|security vulnerability|"
        r"cascading failure|operational overhead|scaling limitation"
    ),
    "low": r"risk|concern|careful|consider",
    "none": r"(?!.*)",  # Match nothing
}

# Pack display info
PACK_ICONS = {
    "staff-core": "🧙",
    "on-call": "📟",
    "security": "🔒",
}

DEFAULT_PACKS = ["staff-core", "on-call", "security"]
DEFAULT_RISK_THRESHOLD = "high"


def detect_blocking_issues(content: str, threshold: str = "high") -> bool:
    """Detect if review content contains blocking issues based on threshold."""
    if threshold == "none":
        return False

    threshold = threshold.lower() if threshold else DEFAULT_RISK_THRESHOLD
    pattern = RISK_PATTERNS.get(threshold, RISK_PATTERNS[DEFAULT_RISK_THRESHOLD])

    return bool(re.search(pattern, content, re.IGNORECASE))


def get_risk_threshold(value: str | None) -> str:
    """Get risk threshold from input, validating and defaulting as needed."""
    if not value:
        return DEFAULT_RISK_THRESHOLD

    value_lower = value.lower()
    if value_lower in RISK_PATTERNS:
        return value_lower

    return DEFAULT_RISK_THRESHOLD


def format_pr_comment(
    review_content: str,
    pack: str,
    blocking: bool,
    max_length: int = 60000,
) -> str:
    """Format review content as a GitHub PR comment."""
    icon = PACK_ICONS.get(pack, "📋")
    blocking_badge = "⚠️ **BLOCKING ISSUES DETECTED**\n\n" if blocking else ""

    if len(review_content) > max_length:
        review_content = review_content[:max_length] + "\n\n... _(review truncated)_"

    comment = f"{blocking_badge}## {icon} Greybeard Review: {pack}\n\n{review_content}"

    return comment


def format_pr_comment_with_metadata(
    review_content: str,
    pack: str,
    blocking: bool,
    commit_sha: str | None = None,
    base_branch: str | None = None,
) -> str:
    """Format review with GitHub metadata footer."""
    comment = format_pr_comment(review_content, pack, blocking)

    footer_parts = ["Greybeard"]
    if commit_sha:
        footer_parts.append(f"[{commit_sha[:7]}]")
    if base_branch:
        footer_parts.append(f"→ {base_branch}")

    footer = " ".join(footer_parts)
    comment += f"\n\n---\n_Review generated by {footer}_"

    return comment


def create_check_payload(
    name: str,
    status: str,
    conclusion: str,
    title: str,
    summary: str,
    text: str | None = None,
) -> dict[str, Any]:
    """Create a GitHub Check Run payload."""
    payload: dict[str, Any] = {
        "name": name,
        "status": status,
        "conclusion": conclusion,
        "output": {
            "title": title,
            "summary": summary,
        },
    }

    if text:
        output = payload["output"]
        assert isinstance(output, dict)
        output["text"] = text

    return payload


def read_diff_file(path: str) -> str:
    """Read a git diff file."""
    return Path(path).read_text()


@dataclass
class DiffSizeInfo:
    """Information about diff size."""

    line_count: int
    char_count: int
    size_category: str


def get_diff_size_info(diff_content: str) -> DiffSizeInfo:
    """Analyze diff size information."""
    line_count = len(diff_content.splitlines())
    char_count = len(diff_content)

    if line_count > 2000:
        category = "Very Large"
    elif line_count > 500:
        category = "Large"
    elif line_count > 100:
        category = "Medium"
    else:
        category = "Small"

    return DiffSizeInfo(
        line_count=line_count,
        char_count=char_count,
        size_category=category,
    )


def has_binary_files(diff_content: str) -> bool:
    """Check if diff contains binary files."""
    return bool(re.search(r"Binary files .* differ", diff_content))


def parse_pack_list(pack_str: str | None) -> list[str]:
    """Parse pack list from comma-separated string."""
    if not pack_str:
        return DEFAULT_PACKS

    return [p.strip() for p in pack_str.split(",") if p.strip()]


def get_packs_to_review(pack_str: str | None) -> list[str]:
    """Get packs to review, using defaults if not specified."""
    if pack_str:
        return parse_pack_list(pack_str)
    return DEFAULT_PACKS


def validate_pack_names(packs: list[str]) -> bool:
    """Validate that pack names are available."""
    for pack_name in packs:
        try:
            load_pack(pack_name)
        except (FileNotFoundError, ValueError):
            return False
    return True


def should_block_pr(review_content: str, threshold: str) -> bool:
    """Determine if a PR should be blocked based on review content."""
    return detect_blocking_issues(review_content, threshold)


def generate_blocking_summary(issues: list[str]) -> list[str]:
    """Generate summary of blocking issues."""
    return [f"- {issue}" for issue in issues if issue]


def get_github_env() -> dict[str, str]:
    """Get GitHub environment variables."""
    return {
        "sha": os.getenv("GITHUB_SHA", "unknown"),
        "ref": os.getenv("GITHUB_REF", "unknown"),
        "base_ref": os.getenv("GITHUB_BASE_REF", "main"),
        "repo": os.getenv("GITHUB_REPOSITORY", "unknown"),
        "event_name": os.getenv("GITHUB_EVENT_NAME", "unknown"),
    }


def get_greybeard_config_from_env() -> dict[str, str]:
    """Get Greybeard configuration from environment variables."""
    return {
        "llm_backend": os.getenv("GREYBEARD_LLM_BACKEND", "openai"),
        "llm_model": os.getenv("GREYBEARD_LLM_MODEL", "gpt-4o"),
        "llm_base_url": os.getenv("GREYBEARD_LLM_BASE_URL", ""),
        "risk_threshold": os.getenv("GREYBEARD_RISK_THRESHOLD", DEFAULT_RISK_THRESHOLD),
        "packs": os.getenv("GREYBEARD_PACKS", ",".join(DEFAULT_PACKS)),
        "mode": os.getenv("GREYBEARD_MODE", "review"),
    }


def validate_github_env() -> bool:
    """Validate that required GitHub environment variables are present."""
    required = ["GITHUB_SHA", "GITHUB_REPOSITORY"]
    missing = [var for var in required if not os.getenv(var)]

    if missing:
        raise ValueError(f"Missing required GitHub env vars: {missing}")

    return True


def validate_llm_credentials(backend: str) -> bool:
    """Validate that LLM credentials are available."""
    api_key_var = {
        "openai": "OPENAI_API_KEY",
        "anthropic": "ANTHROPIC_API_KEY",
        "ollama": None,
        "lmstudio": None,
    }.get(backend.lower())

    if api_key_var is None:
        return True

    return bool(os.getenv(api_key_var))


def find_existing_comment(comments: list[dict[str, Any]], pack: str) -> dict[str, Any] | None:
    """Find an existing Greybeard comment for a pack."""
    for comment in comments:
        if f"Greybeard Review: {pack}" in comment.get("body", ""):
            return comment
    return None


def should_update_comment(existing_comment: dict[str, Any] | None) -> bool:
    """Determine if we should update an existing comment or create new."""
    return existing_comment is not None


@dataclass
class ReviewResult:
    """Result of a single review."""

    pack: str
    review_content: str
    blocking: bool
    error: str | None = None


def run_github_action(
    diff_path: str,
    pack: str,
    risk_threshold: str = DEFAULT_RISK_THRESHOLD,
    config: GreybeardConfig | None = None,
) -> ReviewResult:
    """Run a single Greybeard review for a pack."""
    if config is None:
        config = GreybeardConfig.load()

    diff_content = read_diff_file(diff_path)
    content_pack = load_pack(pack)

    request = ReviewRequest(
        mode="review",
        pack=content_pack,
        input_text=diff_content,
    )

    review_content = run_review(request, config)
    blocking = detect_blocking_issues(review_content, risk_threshold)

    return ReviewResult(
        pack=pack,
        review_content=review_content,
        blocking=blocking,
    )


def run_github_action_safe(
    diff_path: str,
    pack: str,
    risk_threshold: str = DEFAULT_RISK_THRESHOLD,
) -> ReviewResult:
    """Run a Greybeard review with error handling."""
    try:
        return run_github_action(diff_path, pack, risk_threshold)
    except Exception as e:
        return ReviewResult(
            pack=pack,
            review_content=f"Error during review: {str(e)}",
            blocking=False,
            error=str(e),
        )


def process_multiple_packs(
    diff_path: str,
    packs: list[str] | None = None,
    risk_threshold: str = DEFAULT_RISK_THRESHOLD,
) -> list[ReviewResult]:
    """Run reviews for multiple packs."""
    if packs is None:
        packs = DEFAULT_PACKS

    results = []
    for pack in packs:
        result = run_github_action_safe(diff_path, pack, risk_threshold)
        results.append(result)

    return results
